const { center, left, right, stringLength } = require('../');

console.log(`${right('test 0', 0)}|`);
console.log(`${right('test 8', 8)}|`);
console.log(`${right('test 10', 8)}|`);
console.log(`|${left('test 0', 0)}`);
console.log(`|${left('test 8', 8)}`);
console.log(`|${left('test 10', 15)}`);
console.log('stringLength("test")', stringLength('test'));
console.log(`|${left(0, 10)}|`);
console.log(`|${left(1, 11)}|`);
console.log(`|${left(2, 12)}|`);
console.log(`|${left(3, 13)}|`);
console.log(`|${left(4, 14)}|`);
console.log(`|${left(5, 15)}|`);
console.log(`|${center(0, 10)}|`);
console.log(`|${center(1, 11)}|`);
console.log(`|${center(2, 12)}|`);
console.log(`|${center(3, 13)}|`);
console.log(`|${center(4, 14)}|`);
console.log(`|${center(5, 15)}|`);
console.log(`|${right(0, 10)}|`);
console.log(`|${right(1, 11)}|`);
console.log(`|${right(2, 12)}|`);
console.log(`|${right(3, 13)}|`);
console.log(`|${right(4, 14)}|`);
console.log(`|${right(5, 15)}|`);

console.log(`|${center('test', 10)}|`);
console.log(`|${center('tests', 10)}|`);
